### ISSUE TITLE
Allow std to be specified as package spec

### ISSUE THREAD

**Issue by dullbananas** [rust-lang/wg-cargo-std-aware#83] opened 2023-04-23 15:39 UTC
When running this command, `std` is not recognized

```
cargo +nightly clean -p std -Z build-std
```

**Comment by ehuss** [comment] 2023-04-23 16:33
Thanks for the report!  I believe this is a duplicate of #26, so closing as a duplicate of that.

**Closed as not planned by ehuss** 2023-04-23 16:33 UTC
